version: '{build}'
image: Visual Studio 2017

branches:
  except:
    - gh-pages

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cinst ant
  - git submodule update --init --recursive

build_script:
  - ant -f build-applet.xml build
  - ant -f build-reader.xml package
  - ant -f build-standalone.xml package