os: linux
dist: bionic
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - libmbedtls-dev
    - libtomcrypt-dev
    - libtommath-dev
    - libssl-dev
    - libcrypto++-dev
    - libgcrypt20-dev
    - nettle-dev
    - gcc-8
    - g++-8
language: java
jdk: openjdk8
env:
  - CC=gcc-8 CXX=g++-8

install:
  - eval "$(gimme 1.13)"
  - cd ext/boringssl
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=1 ..
  - make crypto
  - cd ../../..
  - cd ext/libressl
  - ./autogen.sh
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=ON ..
  - make crypto
  - cd ../../..

script:
  - ant -f build-applet.xml build
  - ant -f build-reader.xml package
  - ant -f build-standalone.xml package
  - ./util/test.sh

before_deploy:
  - zip "dist/ECTester.zip" "dist/ECTesterReader-dist.jar" "dist/ECTesterReader.jar" "applet/ectester221.cap" "applet/ectester222.cap" "dist/ECTesterStandalone-dist.jar" "dist/ECTesterStandalone.jar"

deploy:
  provider: releases
  token:
    secure: q2aJvu32K+nfbMR60nFCEkn+jYCKprlCRlIoPjuRz1HySX233Ccwpx1CAdNzEjY6FDFcoReKAg6r5vdPjJ4FRPAQ23TxffIYZPkykL5K/pUZJbM5xkazJY0Fp8i6Vyl0JfeanVib1PTyOSugplhCttFk5nb9JUFV36Tre66XntOl5y80Trn94F5aTlRjfW26UH65W7Aa6WZ0N4OX/ZsX+vEOJPAu+RLfOq9oBOx/loB8ntYM/e/6bEwJp6EedRQLDsiS4NavP3svH+GXsPLs5p3soyRXYsvvGKVnVjcjZURxDDdxv5YuCWUUfl9PbNB+Mqmx/HQxl50BKoKFqwap1+TnlbuTAiWaXeh3zdXuGB+TPg8KE8h6ueDneHd3Lpivgq79IvPWIH+N4b3Pa952+rD+JKBZ807efB+97OtWrkQL7/sLZESQUdIszE724HHOiArKpNajIX+kN6NJdul5xFCiQQHG+O7iDFQBavCGM9fk63mZRyGPxZQzS06BV2vIIHg0yx3igN+OKKMFCH+P3hYR1zL6o65OlgbL1ifTZ18GDvmVRNdi53/fxQ2n/mQmI4tQpn4ZB7Ddoxx4GlpjFjzdKk/P9nKwng0M9wrp8row/vb5S+1aPwSxp9/4ASP9dkvLcNjTkWhmGPrWe+82Y9JPK47uesx0YeaVI2C7IR0=
  file:
    - "dist/ECTesterReader-dist.jar"
    - "dist/ECTesterReader.jar"
    - "applet/ectester221.cap"
    - "applet/ectester222.cap"
    - "dist/ECTesterStandalone-dist.jar"
    - "dist/ECTesterStandalone.jar"
    - "dist/ECTester.zip"
  cleanup: false
  on:
    tags: true
    repo: crocs-muni/ECTester
